sys-fs/fuse: disable -flto in ~arch ebuilds, bug #663518
Due to https://gcc.gnu.org/PR91186 gcc-9 in -lto mode does not do work
parition correctly for symbols introduced with `asm .symver`. That
causes linker failures in form of:
    <artificial>:(.text+0xdafe): undefined reference to `__fuse_read_cmd@'

To work it around we filter out -flto flags (already done
for masked ebuilds).

Bug: https://gcc.gnu.org/PR91186
Closes: https://bugs.gentoo.org/663518
Package-Manager: Portage-2.3.69, Repoman-2.3.16
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>