www-servers/tomcat: fix startup via catalina.sh
Previously, we got the following when trying to start tomcat via
catalina.sh:
"""
SEVERE [main] org.apache.tomcat.util.digester.Digester.startElement Begin event threw error
java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletRequest
[...]
"""

So this adds '--with-dependencies' to CLASSPATH in catalina.sh which
fixes the error.