dev-python/pytest-aiohttp: 0.3.0-r1 revbump to require pytest-5.4
Solves this issue:

/usr/lib64/python3.6/site-packages/pytest_asyncio/plugin.py:39: in pytest_pycollect_makeitem
    item = pytest.Function.from_parent(collector, name=name)
E   AttributeError: type object 'Function' has no attribute 'from_parent'

See: https://github.com/gentoo/gentoo/pull/15435#discussion_r412989852
Package-Manager: Portage-2.3.99, Repoman-2.3.22
Signed-off-by: Zac Medico <zmedico@gentoo.org>