dev-python/pywayland: add a missing BDEPEND for wayland-scanner
AssertionError: Specified Wayland protocol file, /usr/share/wayland/wayland.xml, does not exist please specify valid protocol file
 * ERROR: dev-python/pywayland-0.4.15::gentoo failed (compile phase)

Signed-off-by: Joonas Niilola <juippis@gentoo.org>