dev-util/strace: Fix ebuilds to support musl libc
This change resolves a compilation error: typedef redefinition with
different types.

(cherry picked from commit 274bc28b9e69b3571994f29ebcb69bbeb1e0a34f)
Signed-off-by: Robin H. Johnson <robbat2@gentoo.org>
Fixes: https://github.com/gentoo/gentoo/pull/4008