x11-misc/polybar: add ipc.h header from https://github.com/i3/i3/blob/next/include/ipc.h
fix:
In file included from /var/tmp/portage/x11-misc/polybar-3.4.2/work/polybar/lib/i3ipcpp/src/ipc.cpp:10:
/var/tmp/portage/x11-misc/polybar-3.4.2/work/polybar/lib/i3ipcpp/include/i3ipc++/ipc.hpp:12:10: fatal error: i3/ipc.h: No such file or directory
   12 | #include <i3/ipc.h>
      |          ^~~~~~~~~~
compilation terminated.

this error appear with i3wm USE enabled  since it requiere i3icpp