net-irc/irker: irk and irkerhook.py are not python3 friendly
  $ /usr/lib/python-exec/python3.4/irk foo bar
  Traceback (most recent call last):
    File "/usr/lib/python-exec/python3.4/irk", line 50, in <module>
      main()
    File "/usr/lib/python-exec/python3.4/irk", line 41, in main
      message = message.decode('string_escape')
  AttributeError: 'str' object has no attribute 'decode'

  $ /usr/lib/python-exec/python3.4/irkerhook.py
    File "/usr/lib/python-exec/python3.4/irkerhook.py", line 432
      print message
                  ^
  SyntaxError: Missing parentheses in call to 'print'

Package-Manager: portage-2.2.26