net-misc/electrum: missing dependency pyperclip
The program was failing to run with the following error:

  1.66 | E | daemon.Daemon | GUI raised exception: ModuleNotFoundError("No module named 'pyperclip'"). shutting down.
  1.66 | E | __main__ | daemon.run_gui errored
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.11/electrum", line 461, in handle_cmd
    d.run_gui(config, plugins)
  File "/usr/lib/python3.11/site-packages/electrum/daemon.py", line 591, in run_gui
    gui = __import__('electrum.gui.' + gui_name, fromlist=['electrum'])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/electrum/gui/text.py", line 9, in <module>
    import pyperclip
ModuleNotFoundError: No module named 'pyperclip'

which has been fixed by adding the dependency dev-python/pyperclip.

Signed-off-by: Efe İzbudak <efe.izbudak@metu.edu.tr>