www-client/firefox: USE=debug requires bundled libaom
Firefox bundles <libaom-2 and will fail with USE=debug like

> firefox-83.0/image/decoders/nsAVIFDecoder.cpp:301:54: error: use of undeclared identifier 'AOM_PLANE_ALPHA'
>   MOZ_ASSERT(img->stride[AOM_PLANE_Y] == img->stride[AOM_PLANE_ALPHA]);

Link: https://aomedia.googlesource.com/aom/+/f1570f0c2f70832dd170285f8de60bd2379c8efa%5E%21/
Signed-off-by: Thomas Deutschmann <whissi@gentoo.org>