app-text/pdf2djvu: version bump, fix compile error
The current ebuilds all fail to compile with:

	In file included from /usr/lib/gcc/i686-pc-linux-gnu/8.3.0/include/g++-v8/i686-pc-linux-gnu/bits/messages_members.h:36,
	                 from /usr/lib/gcc/i686-pc-linux-gnu/8.3.0/include/g++-v8/bits/locale_facets_nonio.h:2010,
	                 from /usr/lib/gcc/i686-pc-linux-gnu/8.3.0/include/g++-v8/locale:41,
	                 from /usr/lib/gcc/i686-pc-linux-gnu/8.3.0/include/g++-v8/iomanip:43,
	                 from pdf-backend.cc:23:
	/usr/include/libintl.h:61:14: error: ambiguating new declaration of 'char* ngettext(const char*, const char*, long unsigned int)'
	 extern char *ngettext (const char *__msgid1, const char *__msgid2,
	              ^~~~~~~~
	In file included from pdf-backend.hh:52,
	                 from pdf-backend.cc:16:
	i18n.hh:43:28: note: old declaration 'const char* ngettext(const char*, const char*, long unsigned int)'
	 static inline const char * ngettext(const char *message_id, const char *message_id_plural, unsigned long int n)
	                            ^~~~~~~~
	make: *** [<builtin>: pdf-backend.o] Error 1

Removing the offending line from i18n.hh fixes the compile error.

Bump to latest upstream version while we're at it.

Bug: https://bugs.gentoo.org/703566
Signed-off-by: Peter Gantner <gentoo@nephros.org>