media-sound/alsa-tools: gatekeep hwmixvolume behind USE="gtk"
hwmixvolume requires gtk, as per both the README[1] and attempting to
run it on a system without the required dependencies:

  $ hwmixvolume
  Traceback (most recent call last):
    File "/usr/bin/hwmixvolume", line 21, in <module>
      gi.require_version('Gtk', '3.0')
      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
    File "/usr/lib/python3.13/site-packages/gi/__init__.py", line 125, in require_version
      raise ValueError('Namespace %s not available for version %s' %
                       (namespace, version))
  ValueError: Namespace Gtk not available for version 3.0

Hence, as it is ineffective without gtk, gatekeep its installation
behind the already existing gtk USE flag.

[1] https://github.com/alsa-project/alsa-tools/blob/d444519df40d52de3903513a14085a0619f688db/hwmixvolume/README

Signed-off-by: Rahul Sandhu <nvraxn@posteo.uk>
Merges: https://codeberg.org/gentoo/gentoo/pulls/27
Signed-off-by: Eli Schwartz <eschwartz@gentoo.org>