dev-libs/atf: fix unexpected error during configure
conftest.c:26:6: error: a function declaration without a prototype is
deprecated in all versions of C [-Werror,-Wstrict-prototypes]
   26 | main ()
         |      ^
               |       void
               1 error generated.

it had been fixed in autoconf already, so run eautoreconf to regenerate
configure

Closes: https://bugs.gentoo.org/879659
Signed-off-by: Z. Liu <zhixu.liu@gmail.com>