sys-libs/pam: make docs build respect doc use flag
This fixes the meson docs arg to depend on the doc use
flag to be able to turn off documentation in the pam build.

This is necessary because for reasons that aren't fully
understood, on my system xsltproc fails to find the files
installed by app-text/docbook-xsl-ns-stylesheets.

As a result the build fails so making it optional via a
doc USE flag allows to workaround the issue in case the
docs are not required.

pam-1.7.0_p20241230-r3: FAILED: doc/man/misc_conv.3
pam-1.7.0_p20241230-r3: /usr/bin/xsltproc -o doc/man/misc_conv.3 --nonet --xinclude --path /build/asurada/tmp/portage/sys-libs/pam-1.7.0_p20241230-r3/work/linux-pam-e634a3a9be9484ada6e93970dfaf0f055ca17332/doc/man --stringparam profile.condition 'without_vendordir;no_openssl_hmac'
doc/custom-man.xsl ../linux-pam-e634a3a9be9484ada6e93970dfaf0f055ca17332/doc/man/misc_conv.3.xml
pam-1.7.0_p20241230-r3: error : Resource temporarily unavailable: getaddrinfo failed
pam-1.7.0_p20241230-r3: warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl-ns/current/manpages/profile-docbook.xsl"
pam-1.7.0_p20241230-r3: compilation error: file doc/custom-man.xsl line 3 element import
pam-1.7.0_p20241230-r3: xsl:import : unable to load http://docbook.sourceforge.net/release/xsl-ns/current/manpages/profile-docbook.xsl
pam-1.7.0_p20241230-r3: ninja: build stopped: subcommand failed.

Signed-off-by: Adrian Ratiu <adrian.ratiu@collabora.com>