net-misc/httpstat: disable py3.14
py3.14 doesn't work:
```
  File "/usr/lib/python3.14/site-packages/setuptools/build_meta.py", line 317, in run_setup
    exec(code, locals())
    ~~~~^^^^^^^^^^^^^^^^
  File "<string>", line 30, in <module>
  File "<string>", line 17, in get_version
AttributeError: 'Constant' object has no attribute 's'
 * ERROR: net-misc/httpstat-1.3.1-r1::gentoo failed (compile phase):
 *   Wheel build failed
 *
```

I didn't notice because of wheel reuse (now disabled it).

Fixes: 56ba436ee30df1ed54a88e9cd895505c3955d184
Signed-off-by: Sam James <sam@gentoo.org>