dev-util/umockdev: drop -Werror=unused-variable (for Vala)
Exposed by a change in Meson to stop inhibiting Vala warnings, e.g.
```
umockdev-record.p/src/umockdev-pcap.c: At top level:
umockdev-record.p/src/umockdev-pcap.c:101:20: error: ‘umockdev_ioctl_usb_pcap_handler_properties’ defined but not used [-Werror=unused-variable]
  101 | static GParamSpec* umockdev_ioctl_usb_pcap_handler_properties[UMOCKDEV_IOCTL_USB_PCAP_HANDLER_NUM_PROPERTIES];
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

See https://github.com/mesonbuild/meson/commit/5f659af870011e74299d1455a65c2cd5f5ace51f.

Closes: https://bugs.gentoo.org/919380
Signed-off-by: Sam James <sam@gentoo.org>