dev-cpp/gtkmm: Restrict <gtkmm-4.20:4 to <gtk-4.20
Bumping gtk to 4.20.1 exposed a compilation error caused by
conflicting C++ alias declarations in gtk/src/iconpaintable.h:

  using GtkIconPaintable = struct _GtkIconPaintable;
  using GtkIconPaintableClass = struct _GtkIconPaintableClass;

Specifically, the build fails with errors like:

  error: conflicting declaration
  using GtkIconPaintableClass = struct _GtkIconPaintableClass;

These aliases were introduced in commit 04ab9653 (probably) and later
removed in commit 94959145, which fixed the conflict.

Bug: https://bugs.gentoo.org/963805
Signed-off-by: Lukas Schmelting <lschmelting@posteo.com>