net-libs/libssh: Set -DWITH_STACK_PROTECTOR=OFF
The build system injects -fstack-protector _after_ CFLAGS, which means
that when CFLAGS define a stronger SSP, this lowers its protection
instead of improving it.

Additionally, the test for the compiler flag succeeds on HPPA when it
shouldn't, causing the build to fail later on:

In file included from src/agent.c:53:0:
include/libssh/priv.h:169:4: error: #error "Your system must provide a __func__ macro"

Bug: https://bugs.gentoo.org/59506
Package-Manager: Portage-2.3.48, Repoman-2.3.10