media-libs/x265: Let everybody have detect512
Upstream commit d55132eb4201 introduced detect512() but the function is
defined only when X265_ARCH_X86 so the linker fails with non x86
targets:

libx265.so.165: undefined reference to `x265_12bit::detect512()'
libx265.so.165: undefined reference to `x265_10bit::detect512()'
libx265.so.165: undefined reference to `x265::detect512()'

Fix it by defining the function unconditionally.

Package-Manager: Portage-2.3.51, Repoman-2.3.11
Signed-off-by: Jeroen Roovers <jer@gentoo.org>