app-arch/snappy: bump subslot's fudge value due to ABI breakage
Breaks at least dev-qt/qtwebengine:6 if not rebuilt, aka

libQt6WebEngineCore.so.6: undefined reference to
`snappy::RawCompress(char const*, unsigned long, char*, unsigned long*)

 *    ABI: libsnappy.so.1(64) func(+6,-5) [BREAKING]
^ includes RawCompress

Signed-off-by: Ionen Wolkens <ionen@gentoo.org>