profiles/arch/sparc/package.use.mask: mask dev-lang/erlang[hipe]
Build fails as
  error: ‘am_ultrasparc’ undeclared
which is an effect of ./configure bug of sparc32/sparc64 detection.

Needs an upstream fix.

Reported-by: Rolf Eike Beer
Bug: https://bugs.gentoo.org/656618
URL: http://erlang.org/pipermail/erlang-questions/2005-December/018317.html
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>