dev-libs/libdispatch: add USE=test
build system unconditionally was evaluating BUILD_TESTING as true

this leads to build failures in one of the test deps on some arches.

/usr/bin/powerpc64le-unknown-linux-gnu-ld.bfd: tests/libbsdtests.a(bsdtests.c.o): in function `test_ptr_null_format':
bsdtests.c:(.text+0x1d8): undefined reference to `vsnprintf.inline'
/usr/bin/powerpc64le-unknown-linux-gnu-ld.bfd: tests/libbsdtests.a(bsdtests.c.o): in function `test_ptr_notnull_format':
bsdtests.c:(.text+0x478): undefined reference to `vsnprintf.inline'
/usr/bin/powerpc64le-unknown-linux-gnu-ld.bfd: tests/libbsdtests.a(bsdtests.c.o): in function `test_ptr_format':
bsdtests.c:(.text+0x72c): undefined reference to `vsnprintf.inline'
/usr/bin/powerpc64le-unknown-linux-gnu-ld.bfd: tests/libbsdtests.a(bsdtests.c.o): in function `test_ptr_not_format':
bsdtests.c:(.text+0x9dc): undefined reference to `vsnprintf.inline'
/usr/bin/powerpc64le-unknown-linux-gnu-ld.bfd: tests/libbsdtests.a(bsdtests.c.o): in function `test_uint32_format':
bsdtests.c:(.text+0xc8c): undefined reference to `vsnprintf.inline'
/usr/bin/powerpc64le-unknown-linux-gnu-ld.bfd: tests/libbsdtests.a(bsdtests.c.o):bsdtests.c:(.text+0xf3c): more undefined references to `vsnprintf.inline' follow

explicitly passing -DBUILD_TESTINF=OFF allows to skip building and
linking offending test.
Library works well on ppc64le, just the test does not build with 128bit
ieee-long-double toolchain due to old headers somewhere in test deps.

The actual falure will still be visible with FEATURES="test"
but only on ppc64le systems with USE=ieee-long-double toolchain.

Signed-off-by: Georgy Yakovlev <gyakovlev@gentoo.org>