dev-python/scipy: mark as -hppa
This reverts commit e8f2dcda97e4dc66512a41dd6baaaf41a2b46e05.

Can't be built:
```
/var/tmp/portage/dev-python/scipy-1.7.2/work/scipy-1.7.2-python3_9/scipy/stats/_boost/include/func_defs.hpp:96:33:   required from ‘RealType boost_isf(RealType, const Args ...) [with Dst = boost::math::beta_distribution; RealType = long double; Args = {long double, long double}]’
scipy/stats/_boost/src/beta_ufunc.cxx:3902:46:   required from here
/var/tmp/portage/dev-python/scipy-1.7.2/work/scipy-1.7.2-python3_9/scipy/_lib/boost/boost/math/tools/promotion.hpp:148:37: error: static assertion failed: Sorry, but this platform does not have sufficient long double support for the special functions to be reliably implemented.
  148 |          BOOST_STATIC_ASSERT_MSG((0 == ::boost::is_same<type, long double>::value), "Sorry, but this platform does not have sufficient long double support for the special functions to be reliably implemented.");
      |                                  ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Bug: https://bugs.gentoo.org/804115
Signed-off-by: Sam James <sam@gentoo.org>