media-gfx/opentoonz: update opencv dependency
"features2d" is required, otherwise, the build fails due to a missing
header file, causing the following error:

> no member named 'CALIB_CB_FILTER_QUADS' in namespace 'cv'

Signed-off-by: Z. Liu <zhixu.liu@gmail.com>