net-analyzer/wapiti: add important runtime version cap
Now that tests kinda sorta ***work***, we can see by testing, that we
have bad dependencies installed. This project is NOT compatible with
current httpx. The version cap results in around a hundred test failures
disappearing. Some of them start failing instead because of network
sandboxing, so add PROPERTIES for this.

We're down to two failures:

```
===================================== short test summary info =====================================
FAILED tests/attack/test_mod_log4shell.py::test_verify_dns - ValueError: nameserver  is not a dns.nameserver.Nameserver instance or text form, IP address, nor a valid https URL
FAILED tests/cli/test_options.py::test_options - AssertionError: assert 11 == (11 + 1)
===================== 2 failed, 231 passed, 96 warnings in 120.44s (0:02:00) ======================
 * ERROR: net-analyzer/wapiti-3.1.7-r1::gentoo failed (test phase):
 *   pytest failed with python3.11
```

Bug: https://bugs.gentoo.org/952156
Signed-off-by: Eli Schwartz <eschwartz@gentoo.org>