app-emulation/qemu: Add missing ninja BDEPEND
```
ERROR: Cannot find Ninja

 * ERROR: app-emulation/qemu-7.2.8::portage-stable failed (configure phase):
 *   configure failed
 *
 * Call stack:
 *               ebuild.sh, line  125:  Called src_configure
 *             environment, line 5053:  Called qemu_src_configure 'softmmu'
 *             environment, line 4914:  Called die
 * The specific snippet of code:
 *       ../configure "${conf_opts[@]}" || die "configure failed"
```

Signed-off-by: Raul E Rangel <rrangel@chromium.org>