net-dns/pdns: migrate to lua-single.eclass
As nice and easy as dnsdist. Builds, fails tests in exactly the same way [1]
and installs fine against all implementations currently in the tree.

It also makes sure RDEPEND is only set once in the ebuild.

[1] One failure: "test-nameserver_cc.cc(46): error: in "test_nameserver_cc/test_AddressIsUs6": check AddressIsUs(local3) == true has failed [false != true]"

Closes: https://bugs.gentoo.org/752801
Signed-off-by: Marek Szuba <marecki@gentoo.org>