dev-python/gevent: bump libev dep
EVBACKEND_LINUXAIO was added to libev-4.24
EVBACKEND_IOURING was added in libev-4.31

```
src/gevent/libev/corecext.c: In function '__pyx_pymod_exec_corecext':
src/gevent/libev/corecext.c:24279:36: error: 'EVBACKEND_LINUXAIO' undeclared (first use in this function)
24279 |   __pyx_t_1 = __Pyx_PyInt_From_int(EVBACKEND_LINUXAIO); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 113, __pyx_L1_error)
      |                                    ^~~~~~~~~~~~~~~~~~
src/gevent/libev/corecext.c:24279:36: note: each undeclared identifier is reported only once for each function it appears in
src/gevent/libev/corecext.c:24284:36: error: 'EVBACKEND_IOURING' undeclared (first use in this function); did you mean 'EVBACKEND_PORT'?
24284 |   __pyx_t_1 = __Pyx_PyInt_From_int(EVBACKEND_IOURING); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 114, __pyx_L1_error)
      |                                    ^~~~~~~~~~~~~~~~~
```

Signed-off-by: Robin H. Johnson <robbat2@gentoo.org>