sys-devel/distcc: revbump, fix distcc-config py2<-> py3 errors
error:
Creating symlinks...
Creating /usr/lib/distcc/bin/gcc symlink...
Creating /usr/lib/distcc/bin/cc symlink...
Creating /usr/lib/distcc/bin/c++ symlink...
Creating /usr/lib/distcc/bin/g++ symlink...
Traceback (most recent call last):
  File "/usr/bin/distcc-config", line 154, in <module>
    installlinks()
  File "/usr/bin/distcc-config", line 93, in installlinks
    lines = p.stdout.read().rstrip().split('\n')
TypeError: a bytes-like object is required, not 'str'

throw in extra .decode() to stdout.read()

Package-Manager: Portage-2.3.52, Repoman-2.3.12
Signed-off-by: Georgy Yakovlev <gyakovlev@gentoo.org>