gui-apps/wayvnc: fix neatvnc dependency
wayvnc[gbm] requires gui-libs/neatvnc to be built with gbm enabled,
otherwise `wayvnc -g` would segfault with following error:

ERROR: ../neatvnc-0.9.4/src/fb.c: 107: nvnc_fb_from_gbm_bo was not enabled during build time

Signed-off-by: Michael Mair-Keimberger <mm1ke@gentoo.org>