dev-db/mysql-connector-c: Further OpenSSL 1.1 compile fix
Fix viossl.c:430:44: error: dereferencing pointer to incomplete type
 ‘SSL_COMP {aka struct ssl_comp_st}’ error

Backported changes from newer MySQL versions

Closes: https://bugs.gentoo.org/658910
Package-Manager: Portage-2.3.49, Repoman-2.3.10