net-print/cups-filters: fix compile failure
/usr/include/qpdf/QPDFWriter.hh:560:32: error: ‘std::string_view’ has not been declared
std::string_view was introduced in c++17, and the ebuild was compiled with c++11, so the error occurs.

Bug: https://bugs.gentoo.org/898156
Signed-off-by: Yu Gu <guyu2876@gmail.com>
Closes: https://github.com/gentoo/gentoo/pull/29831
Signed-off-by: Sam James <sam@gentoo.org>