media-libs/libsdl2: enable cocoa on osx
Required for building on osx prefix, otherwise you get the following
build failures:

Undefined symbols for architecture x86_64:
  "_Cocoa_IsWindowInFullscreenSpace", referenced from:
      _SDL_UpdateFullscreenMode in SDL_video.o
      _SDL_OnWindowFocusLost in SDL_video.o
  "_Cocoa_Mtl_AddMetalView", referenced from:
      _METAL_CreateRenderer in SDL_render_metal.o
  "_Cocoa_SetWindowFullscreenSpace", referenced from:
      _SDL_UpdateFullscreenMode in SDL_video.o
ld: symbol(s) not found for architecture x86_64
Package-Manager: Portage-2.3.31, Repoman-2.3.9
Closes: https://github.com/gentoo/gentoo/pull/8200