sci-libs/mumps: -fallow-argument-mismatch for gcc v10
Fixes errors due to new fatala error introduced in gcc v10:

    Error: Type mismatch between actual argument at (1) and
    actual argument at (2) (INTEGER(8)/INTEGER(4)).

Closes: https://bugs.gentoo.org/727356

Signed-off-by: Alexei Colin <acolin@isi.edu>