net-misc/youtube-dl: Add rtmp USE flag
The youtube-dl script supports retrieving videos over the Real Time
Messaging Protocol (RTMP) should that be required. However, in order to
do so it makes use of the rtmpdump program.

  $ youtube-dl <url>
  > ERROR: RTMP download detected but "rtmpdump" could not be run.
  > Please install it.

This change adds a new USE flag 'rtmp' to youtube-dl which pulls in
media-video/rtmpdump as a dependency.

Bug: https://bugs.gentoo.org/639028
Closes: https://bugs.gentoo.org/639028