dev-util/rocminfo: enable release build
The rocminfo CMake file uses a custom variable named ROCRTST_BLD_TYPE to
set CMAKE_BUILD_TYPE. When not set, this defaults to Debug, which adds
-O0 to CXXFLAGS. This overrides the optimization flags in CXXFLAGS in
make.conf.

When the CXXFLAGS in make.conf contain _FORTIFY_SOURCE, this breaks
compilation with the following error:

/usr/include/features.h:412:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
  412 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~

Fix this by setting the ROCRTST_BLD_TYPE variable to Release in
mycmakeargs.

Closes: https://bugs.gentoo.org/887583
Package-Manager: Portage-3.0.30, Repoman-3.0.3
Signed-off-by: Stijn Tintel <stijn@linux-ipv6.be>