net-misc/socat: fix 1.7.4.4 build on musl
The issue with undefined reference to getprotobynumber_r for musl was
fixed in 1.7.4.4 in commit [1]. It is no longer wanted to treat musl
configuration specially.

[1] https://repo.or.cz/socat.git/commitdiff/75cb44bc90577c3487458564ca803163681319f1

Bug: https://bugs.gentoo.org/831016
Closes: https://bugs.gentoo.org/879601
Signed-off-by: Petr Vaněk <arkamar@atlas.cz>
Closes: https://github.com/gentoo/gentoo/pull/28358
Signed-off-by: Sam James <sam@gentoo.org>