Revert "dev-util/redo: Update PYTHON_COMPAT"
>>> Compiling source in
/home/jer/portage/net-libs/wvstreams-99999/work/wvstreams-99999 ...
Traceback (most recent call last):
  File "/usr/bin/redo", line 8, in <module>
    import redo.cmd_redo
  File "/usr/bin/../lib/redo/cmd_redo.py", line 51
    print version.TAG
                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean
print(version.TAG)?

This reverts commit 79802ff71e24c576f500de4ea9c6e9c94200e623.

Signed-off-by: Jeroen Roovers <jer@gentoo.org>