sys-devel/binutils-apple: fix build on macOS 13, including ARM64.
This commits introduces three patches to fix build on macOS 13
(Intel), and also on ARM64 (Apple Silicon).

1. On macOS 13, Gentoo Prefix fails to compile cctools due to
missing Blocks support in GCC, creating the following error:

/Users/ec2-user/gentoo/MacOSX.sdk/usr/include/objc/runtime.h:373:29: error: expected ')' before '^' token
  373 |                       void (^ _Nonnull block)(Class _Nonnull aClass, BOOL * _Nonnull stop)
      |                             ^
      |                             )

Fortunately the header objc-runtime.h is not strictly necessary.
As a workaround, stop including objc-runtime.h in print_objc.c
and print_bitcode.c.

2. In ar(1), strcmp() checks are used to determine the value
of argument argv[1], even when no argument is given. In the
past, they were possibly harmless out-of-bound reads and
comparison with garbage, without consequences.

However, running it on macOS 13 w/ Apple Silicon immediately
crashes it with Segmentation Fault, because argv[1] is now
NULL and generates EXC_BAD_ACCESS in strcmp().

$ ./bin/ar
Segmentation fault: 11

This commit checks whether argc is equal or greater than 2
before doing strcmp(). No revbump is needed since the package
couldn't be built on ARM64 before.

3. Fabian Groffen's downstream patch "fix compilation on arm64",
which adds missing CPU register definitions.

Closes: https://bugs.gentoo.org/905131
Signed-off-by: Yifeng Li <tomli@tomli.me>