media-video/obs-studio: fix dev-qt/qtbase dependency
dev-qt/qtbase with Xorg support is required to build obs-studio, else we
get build errors such as:

/var/tmp/portage/media-video/obs-studio-31.1.1/work/obs-studio-31.1.1/frontend/OBSApp.cpp:1054:60: error: no member named 'QX11Application' in namespace 'QNativeInterface'
 1054 |                 auto native = qGuiApp->nativeInterface<QNativeInterface::QX11Application>();
      |                                                        ~~~~~~~~~~~~~~~~~~^
1 warning and 1 error generated.

Closes: https://bugs.gentoo.org/960634
Signed-off-by: Brahmajit Das <listout@listout.xyz>