gnome-base/librsvg: fix building of .pc w/ cross-compile
target have to be required w/ cross-compile too

>Building pkg-config files
>Error: CliError { error: Some(failed to write `/usr/aarch64-unknown-linux-gnu/
>tmp/portage/gnome-base/librsvg-2.60.0/work/librsvg-2.60.0-.arm64/target/
>x86_64-unknown-linux-gnu/release/librsvg_c.pc`

Signed-off-by: Nicolas PARLANT <nicolas.parlant@parhuet.fr>
Part-of: https://codeberg.org/gentoo/gentoo/pulls/543
Merges: https://codeberg.org/gentoo/gentoo/pulls/543
Signed-off-by: Sam James <sam@gentoo.org>