media-libs/vulkan-loader: add missing xorg-proto dep
Package xproto was not found in the pkg-config search path.
ERROR: media-libs/vulkan-loader-1.3.296.0::gentoo failed (configure phase):

Signed-off-by: Joonas Niilola <juippis@gentoo.org>