dev-util/codeblocks: DisplayEvents.cpp fix linking wxGTK
Ref. https://sourceforge.net/p/codeblocks/code/13653/

Upstream patch to fix 'undefined reference' linker errors by adding
missing wxGTK libraries to the linker flags.

This resolves errors such as:

DisplayEvents.cpp:(.text+0x150b): undefined reference to `wxConvLibcPtr'

See the included patch for additional details and comments.

Package-Manager: portage-3.0.82.2
Closes: https://bugs.gentoo.org/983198
Signed-off-by: Matthew White <mehw.is.me@proton.me>
Part-of: https://github.com/gentoo/gentoo/pull/46831
Signed-off-by: Sam James <sam@gentoo.org>