dev-embedded/u-boot-tools: depend on sys-apps/dtc[python]
If dtc[python] (i.e. pylibfdt) is unavailable, u-boot-tools will build
its own, at least semi-automagically (seems to possibly do something
different with dtc[-python]).

Spotted after a report on IRC w/ a build failure:
> Traceback (most recent call last):
>  File /var/tmp/portage/dev-embedded/u-boot-tools-2025.01/work/u-boot-2025.01/scripts/dtc/pylibfdt/setup.py", line 23, in module
>    from setuptools import setup, Extension
> ModuleNotFoundError: No module named 'setuptools'
> make[2]: *** [scripts/dtc/pylibfdt/Makefile:33: rebuild] Error 1
> make[1]: *** [scripts/Makefile.build:398: scripts/dtc/pylibfdt] Error 2
> make[1]: *** Waiting for unfinished jobs....

This partly but I think not fully handles bug #860300. I don't have it
in me to poke further at that right now.

Bug: https://bugs.gentoo.org/860300
Signed-off-by: Sam James <sam@gentoo.org>