dev-util/mingw64-runtime: fix build against gcc-11 (__rdtsc clash)
gcc-11 defines __rdtsc as a macro:
    // include/ia32intrin.h:110
    #define __rdtsc() __builtin_ia32_rdtsc ()
and causes build failure:
    intrincs/rdtsc.c:15:30:
      error: macro "__rdtsc" passed 1 arguments, but takes just 0
       15 | unsigned __int64 __rdtsc(void)
          |                              ^

Let's avoid __rdtsc definition on systems with #define __rdtsc present.

There is still a chance that it might be a '#define __rdtsc __rdtsc'.
We'll revisit it then.

Reported-by: Mihai Donțu
Closes: https://bugs.gentoo.org/786549
Package-Manager: Portage-3.0.18, Repoman-3.0.3
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>