media-gfx/scrot: depend on imlib2[filters(+)]
It's enabled by default on new imlib2-0.11.0, but if someone happens
to disable it will get: undefined reference to `imlib_apply_filter'.

Seems this was always available on prior versions, so going with (+).

Signed-off-by: Ionen Wolkens <ionen@gentoo.org>