app-emulation/libvirt: version bump to 1.3.4, bug #580418, bug #579960
 - bump to version 1.3.4, bug #580418

 - apply a build system patch for the sysmacros header change, bug #579960
   fixes the compile error "undefined reference to {'major', 'minor'}"
   due to gentoo specific glibc patches (bug #575232)

Package-Manager: portage-2.2.26