www-client/firefox: add a couple of missing deps for 93
 - headers seem to be needed, but libraries not directly linked.
  * /var/tmp/portage/www-client/firefox-93.0/work/firefox-93.0/toolkit/xre/nsNativeAppSupportUnix.cpp:32:12: fatal error: 'X11/ICE/ICElib.h' file not found
  * /var/tmp/portage/www-client/firefox-93.0/work/firefox-93.0/toolkit/xre/nsNativeAppSupportUnix.cpp:33:12: fatal error: 'X11/SM/SMlib.h' file not found

Signed-off-by: Joonas Niilola <juippis@gentoo.org>