app-forensics/zzuf: support musl in configure.ac
One, call AC_USE_SYSTEM_EXTENSIONS so that all compiler invocations have
the correct feature-set macros set. This is required so that configure
can include the musl version of aio.h without

error: field 'aio_sigevent' has incomplete type

Not quite sure WHY this is necessary given that according to musl
documentation, if no feature test macros are defined musl exposes the
equivalent of _BSD_SOURCE - but there you go.

Two, extend the test identifying the way of extracting raw position
index from the structure fpos64_t, so that it supports the musl layout
of this structure as well.

With these two fixes in place zzuf builds successfully against musl.
Tests (which currently have to be run manually because they like neither
the sandbox nor out-of-tree builds) fail but in the same way as against
glibc.

Closes: https://bugs.gentoo.org/714030
Signed-off-by: Marek Szuba <marecki@gentoo.org>