net-ftp/ftp: build with -std=gnu17 in 0.17.34.0.2.5.1
this version of	the package will not compile with c23. 'append-cflags'
was added to the ebuild to use '-std=gnu17' to compile the package
successfully.

The error given with c23:
error: two or more data types in declaration specifiers

Closes: https://bugs.gentoo.org/943875
Signed-off-by: OldManSeph7818 <sschaefering@gmail.com>