app-i18n/xvnkb: run configure with bash
config.h:1:1: error: expected identifier or ‘(’ before ‘-’ token
    1 | -e #ifndef __VK_CONFIG_H

This is just... dandy... I too love unix command flags echo'ed into my
headers...

It uses echo -e to a header, which breaks on non-bash shells and is
generally a problem.

Closes: https://bugs.gentoo.org/886069
Signed-off-by: Eli Schwartz <eschwartz93@gmail.com>
Signed-off-by: Sam James <sam@gentoo.org>