app-arch/stenc: drop 1.1.1
Drop version 1.1.1 which was not GCC-15 compatible yet.
This caused
error: uint8_t has not been declared

Closes: https://bugs.gentoo.org/939692
Signed-off-by: Jonas Stein <jstein@gentoo.org>