dev-qt/qtdeclarative: version 5.15.16 requires SSE2 for USE="jit" and x86 arch
ERROR: Feature 'qml-jit' was enabled, but the pre-condition '   (arch.i386   && tests.pointer_32bit && features.sse2)
             || (arch.x86_64 && tests.pointer_64bit && features.sse2)
             || (arch.arm    && tests.pointer_32bit && tests.arm_fp && tests.arm_thumb
                 && (config.linux || config.ios || config.tvos || config.qnx))
             || (arch.arm64  && tests.pointer_64bit && tests.arm_fp
                 && (config.linux || config.ios || config.tvos || config.qnx || config.integrity))' failed.

Add ```USE_REQUIRED``` for x86 machines without SSE2 support.

Signed-off-by: Cristian Othón Martínez Vera <cfuga@cfuga.mx>