app-emulation/snapd: Bump to version 2.51 and require squashfs-tools[lzma]
Snaps that use xz compression fail to install with squashfs-tools[-lzma]:

error: cannot perform the following tasks:
- Mount snap "snapd" (10492) (cannot run unsquashfs:
-----
Filesystem uses xz compression, this is unsupported by this version
Decompressors available:
        gzip
-----)

Reported-by: Artem Ilgamov <a.ilgamov@myhart.ru>
Closes: https://bugs.gentoo.org/761523
Package-Manager: Portage-3.0.19, Repoman-3.0.3
Signed-off-by: Zac Medico <zmedico@gentoo.org>