app-text/calibre: Added missing part of icu68 patch
Without that missing chunk build fails as follows:

  /var/tmp/portage/app-text/calibre-4.23.0/work/calibre-4.23.0/src/calib
  re/utils/matcher.c:18:23: error: two or more data types in declaration
   specifiers
     18 | typedef unsigned char bool;
        |                       ^~~~

Package-Manager: Portage-3.0.10, Repoman-3.0.2
Signed-off-by: Lars Wendler <polynomial-c@gentoo.org>