sys-apps/portage: version bump to 2.3.40
  #656492 - AttributeError: 'set' object has no attribute 'items'

Closes: https://bugs.gentoo.org/656492
Package-Manager: Portage-2.3.40, Repoman-2.3.9