dev-python/mkdocs-material: drop 8.5.4
hatchling.plugin.exceptions.UnknownPluginError: Unknown metadata hook: nodejs

The newer versions no longer build in pep517 mode,
nor do they build in the legacy non-pep517 mode.

Closes: https://bugs.gentoo.org/873982
Signed-off-by: Andrew Ammerlaan <andrewammerlaan@gentoo.org>