media-sound/gogglesmm: fix conflict with libgap.so
Don't build gap as shared-lib to avoid a conflict with libgap.so from
sci-mathematics/gap. No package links against libgap.so in tree.

Set explicit X for media-libs/libepoxy :
> src/gmdefs.h:32:10:
> fatal error: epoxy/glx.h: No such file or directory
>   32 | #include <epoxy/glx.h>

Clean an old bug from 1.2.1

Bug: https://bugs.gentoo.org/951983
Closes: https://bugs.gentoo.org/917025
Signed-off-by: Nicolas PARLANT <nicolas.parlant@parhuet.fr>
Part-of: https://github.com/gentoo/gentoo/pull/41416
Closes: https://github.com/gentoo/gentoo/pull/41416
Signed-off-by: Sam James <sam@gentoo.org>