sys-libs/compiler-rt: enable atomic builtin
Several packages depend on GCC's libatomic to perform atomic operations.
For example, this compiles without -latomic:
```c
_Atomic struct {
    int v[1];
} a;
atomic_store(&a, a);
```
But this fails with error "undefined reference to __atomic_store_16"
without -latomic:
```c
_Atomic struct {
    int v[4];
} b;
atomic_store(&b, b);
```

LLVM does not have a libatomic.so, but an atomic builtin to support such
operations.  However, it is disabled by default to allow use of system
libatomic while using LLVM as a compiler.  Pure LLVM environments
without GCC installed require this builtin.  This commit adds
`-DCOMPILER_RT_EXCLUDE_ATOMIC_BUILTIN=OFF` cmake option to enable
the builtin.

Bug: https://bugs.gentoo.org/911340
Signed-off-by: mojyack <mojyack@gmail.com>
Closes: https://github.com/gentoo/gentoo/pull/39168
Signed-off-by: Michał Górny <mgorny@gentoo.org>