dev-embedded/u-boot-utils: Add a missing dependency
Fixes a build in Flatcar:

x86_64-pc-linux-gnu-gcc -Wp,-MD,tools/.mkeficapsule.d -Wall -Wstrict-prototypes -O2 -fomit-frame-pointer  -O2 -pipe   -std=gnu11   -DCONFIG_FIT_SIGNATURE -DCONFIG_FIT_SIGNATURE_MAX_SIZE=0xffffffff -DCONFIG_FIT_CIPHER -include ./include/compiler.h -idirafterinclude -idirafter./arch/sandbox/include -I./scripts/dtc/libfdt -I./tools -DUSE_HOSTCC -D__KERNEL_STRICT_NAMES -D_GNU_SOURCE  -I/usr/include/uuid  -Wl,-O2 -Wl,--as-needed -o tools/mkeficapsule tools/mkeficapsule.c   -lgnutls -luuid
tools/mkeficapsule.c:21:10: fatal error: gnutls/gnutls.h: No such file or directory
    21 | #include <gnutls/gnutls.h>
       |          ^~~~~~~~~~~~~~~~~
compilation terminated.

The build system silently ignores missing gnutls by adding nothing to
`CFLAGS` and adding `-lgnutls` to `LDLIBS`.

Signed-off-by: Krzesimir Nowak <knowak@microsoft.com>