dev-python/pytest-salt-factories: needs salt at runtime
Caused a test failure in traitlets:
```
  File "/usr/lib/python3.8/site-packages/saltfactories/utils/__init__.py", line 15, in <module>
    import salt.utils.user
ModuleNotFoundError: No module named 'salt'
 * ERROR: dev-python/traitlets-5.1.1::gentoo failed (test phase):
 *   pytest failed with python3.8
```

Signed-off-by: Sam James <sam@gentoo.org>