dev-libs/vectorscan: fix build failure on x86
```
FAILED: [code=1] CMakeFiles/hs_compile_shared.dir/src/fdr/fdr_engine_description.cpp.o
/usr/bin/i686-pc-linux-gnu-g++ -DNDEBUG -I/var/tmp/portage/dev-libs/vectorscan-5.4.12/work/vectorscan-vectorscan-5.4.12_build -I/var/tmp/portage/dev-libs/vectorscan-5.4.12/work/vectorsca
n-vectorscan-5.4.12 -I/var/tmp/portage/dev-libs/vectorscan-5.4.12/work/vectorscan-vectorscan-5.4.12/src -isystem /var/tmp/portage/dev-libs/vectorscan-5.4.12/work/vectorscan-vectorscan-5.
4.12/include  -O2 -march=pentium4 -mfpmath=sse -pipe -msse4.2   -std=c++17 -Wall -Wextra  -fno-new-ttp-matching -DNDEBUG -Wno-maybe-uninitialized -Wno-uninitialized -fvisibility=hidden -
Wno-unused-but-set-variable -Wno-ignored-attributes -Wno-nonnull -Wno-stringop-overflow -Wno-stringop-overread  -fPIC -MD -MT CMakeFiles/hs_compile_shared.dir/src/fdr/fdr_engine_descript
ion.cpp.o -MF CMakeFiles/hs_compile_shared.dir/src/fdr/fdr_engine_description.cpp.o.d -o CMakeFiles/hs_compile_shared.dir/src/fdr/fdr_engine_description.cpp.o -c /var/tmp/portage/dev-lib
s/vectorscan-5.4.12/work/vectorscan-vectorscan-5.4.12/src/fdr/fdr_engine_description.cpp
/var/tmp/portage/dev-libs/vectorscan-5.4.12/work/vectorscan-vectorscan-5.4.12/src/fdr/fdr_engine_description.cpp: In function ‘u32 ue2::findDesiredStride(size_t, size_t, size_t)’:
/var/tmp/portage/dev-libs/vectorscan-5.4.12/work/vectorscan-vectorscan-5.4.12/src/fdr/fdr_engine_description.cpp:74:37: error: no matching function for call to ‘min(size_t, long unsigned
 int)’
   74 |             desiredStride = std::min(min_len - 1, 2UL);
      |                             ~~~~~~~~^~~~~~~~~~~~~~~~~~
```

Bug: https://bugs.gentoo.org/962120
Signed-off-by: Sam James <sam@gentoo.org>