net-libs/libnetfilter_acct: fix build w/ clang 20
with clang 20 — and possibly earlier versions — the warning
attribute declaration must precede definition [-Wignored-attributes]
causes certain symbols not to be exported. As a result, net-firewall/nfacct
fails to link with errors such as:

> undefined reference to `nfacct_...'

Closes: https://bugs.gentoo.org/740710
Signed-off-by: Z. Liu <zhixu.liu@gmail.com>