x11-libs/wxGTK: Fix missing [X?] on gtk3 dependency
    wxWidgets-3.2.2.1/src/unix/uiactionx11.cpp:35:10: fatal error: 'gdk/gdkx.h' file not found

Signed-off-by: Haelwenn (lanodan) Monnier <contact@hacktivis.me>