dev-python/python-xmp-toolkit: media-libs/exempi is a RDEPEND
Move media-libs/exempi to unconditional RDEPEND, since the package
does not import without it at all:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.12/site-packages/libxmp/__init__.py", line 50, in <module>
    from .core import XMPMeta, XMPIterator
  File "/usr/lib/python3.12/site-packages/libxmp/core.py", line 50, in <module>
    from . import exempi as _cexempi
  File "/usr/lib/python3.12/site-packages/libxmp/exempi.py", line 69, in <module>
    EXEMPI = _load_exempi()
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libxmp/exempi.py", line 60, in _load_exempi
    raise ExempiLoadError('Exempi library not found.')
libxmp.ExempiLoadError: Exempi library not found.
```

Signed-off-by: Michał Górny <mgorny@gentoo.org>