dev-python/pymountboot: add missing pkgconfig BDEPEND
 File "/var/tmp/portage/dev-python/pymountboot-0.2.3-r1/work/pymountboot-0.2.3/setup.py", line 18, in <module>
    cflags, libs = [pkgconfig_get(x, 'mount') for x in ('--cflags', '--libs')]
  File "/var/tmp/portage/dev-python/pymountboot-0.2.3-r1/work/pymountboot-0.2.3/setup.py", line 18, in <listcomp>
    cflags, libs = [pkgconfig_get(x, 'mount') for x in ('--cflags', '--libs')]
  File "/var/tmp/portage/dev-python/pymountboot-0.2.3-r1/work/pymountboot-0.2.3/setup.py", line 11, in pkgconfig_get
    subp = subprocess.Popen(('pkg-config',) + args,
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pkg-config'

Signed-off-by: Joonas Niilola <juippis@gentoo.org>