dev-embedded/u-boot-tools: Fix missing BDEPENDs
This package currently shows the following errors:

```
Traceback (most recent call last):
  File "scripts/dtc/pylibfdt/setup.py", line 23, in <module>
    from setuptools import setup, Extension
ModuleNotFoundError: No module named 'setuptools'
```

```
tools/mkeficapsule.c:21:10: fatal error: 'gnutls/gnutls.h' file not found
```

```
./scripts/dtc-version.sh: line 18: which: command not found
```

This change fixes the errors by not compiling pylibfdt and mkeficapsule.
It also adds the missing `which` dependency.

Signed-off-by: Raul E Rangel <rrangel@chromium.org>
Closes: https://github.com/gentoo/gentoo/pull/32268
Signed-off-by: Sam James <sam@gentoo.org>