media-video/obs-studio: depend on 'qtbase[wayland]' when USE="wayland"
Even though 'QNativeInterface::QWaylandApplicatio' seems to come from
'qtbase[gui]', the build will still fail with
"error: ‘QWaylandApplication’ is not a member of ‘QNativeInterface’;"
if building against 'qtbase[-wayland]'.

Bug:https://bugs.gentoo.org/980717
Signed-off-by: Jimi Huotari <chiitoo@gentoo.org>