sys-process/criu: disable -Werror, bug #679140
gcc-8 detected new warnings and broke the build:
  compel/include/uapi/compel/asm/fpu.h:89:1: error:
    alignment 1 of ‘struct xsave_struct_ia32’ is less than 16
      [-Werror=packed-not-aligned]

The change disables -Werror as we do in unstable ebuilds.

Reported-by: Thomas Beutin
Closes: https://bugs.gentoo.org/679140
Package-Manager: Portage-2.3.62, Repoman-2.3.12
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>