media-gfx/scrot: depend on imlib2[text(+)] too
Should've figured this one would be a problem too.
(undefined reference to `imlib_context_set_angle`)

Signed-off-by: Ionen Wolkens <ionen@gentoo.org>