sys-apps/bleachbit: fix gtk+3 dependency
bleachbit requires gtk+:3[introspection]

ValueError: Namespace Gtk not available

Signed-off-by: orbea <orbea@riseup.net>