dev-haskell/cryptonite: pass -msse2 for blake2, bug #696220
Fixed two problems here:
- blake2 code assumes SSE2, not just SSE
- x86 needs -msse2 to be passed explicitly (as opposed to amd64)

Otherwise compiler does not attempt to emit sse2 primitives
and build fails as:
```
cbits/blake2/sse/blake2-config.h:68:2: error:
     error: #error "This code requires at least SSE2."
     #error "This code requires at least SSE2."
      ^~~~~
```

Reported-by: Thomas Kahle
Closes: https://bugs.gentoo.org/696220
Package-Manager: Portage-2.3.76, Repoman-2.3.17
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>