dev-lang/zig: fix building 0.13.0 with `sys-devel/llvm-18.1.8-r6`
Also, while we are here, sync `.maxrss` fix from 9999 ebuild .
Patch message:

This is backported PR https://www.github.com/ziglang/zig/pull/21862 ,
squashed and trimmed down for Zig 0.13.0 . Fixes following error when
compiling with sys-devel/llvm-18.1.8-r6:
```
/var/tmp/portage/dev-lang/zig-0.13.0/work/zig-0.13.0/src/zig_llvm.cpp:738:68: error: static assertion failed
  738 | static_assert((Triple::EnvironmentType)ZigLLVM_LastEnvironmentType == Triple::LastEnvironmentType, "");
```

Chronology as I understood it:
 * New enum tags were added for `Triple::EnvironmentType` to 20.x in
   https://www.github.com/llvm/llvm-project/pull/111302 ,
 * These additions were backported to 19.1.3 in
   https://www.github.com/llvm/llvm-project/pull/112364 , at this point
   Zig upstream (9999) notices static assert failure and fixes in
   https://www.github.com/ziglang/zig/pull/21862 .
   Discussed here:
   https://www.github.com/llvm/llvm-project/pull/112364#discussion_r1823206017 .
 * These additions were backported again to 18.1.8-r6 (Gentoo only) in
   https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=9455b76daa769c03686d18098dbf37690c5c5f61 ,
   this time it causes static assert failure for 0.13.0 .

Closes: https://bugs.gentoo.org/942563
Signed-off-by: Eric Joldasov <bratishkaerik@landless-city.net>