dev-lisp/roswell: mark as LTO-unsafe
Listen, I definitely know it's LTO-unsafe.

I can't actually get it to compile, but either way, it's definitely
LTO-unsafe...

The next compilation error is:

```
/usr/lib/gcc/x86_64-pc-linux-gnu/13/../../../../x86_64-pc-linux-gnu/bin/ld: warning: resources.o: missing .note.GNU-stack section implies executable stack
/usr/lib/gcc/x86_64-pc-linux-gnu/13/../../../../x86_64-pc-linux-gnu/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
resources.o:(.rsrc$01+0x80): dangerous relocation: R_AMD64_IMAGEBASE with __ImageBase undefined
resources.o:(.rsrc$01+0x90): dangerous relocation: R_AMD64_IMAGEBASE with __ImageBase undefined
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:436: ros] Error 1
```

As you can tell from the linker error, it appears to be lisp code... if
anyone can figure out why it happens you're welcome to it but I am not
spending more time on lisp so this is me backing away now that the LTO
bug can be closed. So long!

Closes: https://bugs.gentoo.org/856106
Signed-off-by: Eli Schwartz <eschwartz93@gmail.com>
Signed-off-by: Sam James <sam@gentoo.org>