dev-qt/qtwebsockets: depend on qtbase:6[ssl]
fatal error: QtNetwork/qsslpresharedkeyauthenticator.h: No such ...

Signed-off-by: Ionen Wolkens <ionen@gentoo.org>