net-mail/mu: Fix building on GCC 13
GCC 13s libstdc++ reduced its dependency on some headers like <cstdint>,
so it's no longer transitively included through various headers.
Include it explicitly.

See also: https://gcc.gnu.org/gcc-13/porting_to.html#header-dep-changes

  ../lib/utils/mu-error.hh:36:26: error: ‘uint32_t’ does not name a type
     36 |         static constexpr uint32_t SoftError = 1 << 23;
        |                          ^~~~~~~~

Closes: https://github.com/gentoo/gentoo/pull/29210
Signed-off-by: Arsen Arsenović <arsen@gentoo.org>