dev-vcs/breezy: Add missing RDEPEND on dev-python/tzlocal
$ brz log
Error: PyErr { type: <class 'ModuleNotFoundError'>, value: ModuleNotFoundError("No module named 'tzlocal'"), traceback: Some(<traceback object at 0x7f007933a240>) }

Acked-by: Arthur Zamarin <arthurzam@gentoo.org>
Signed-off-by: Ulrich Müller <ulm@gentoo.org>