dev-util/codeblocks: autotools fix linking TinyXML
Ref. https://sourceforge.net/p/codeblocks/code/13855/

Upstream patch to fix 'undefined reference' linker errors by adding
missing TinyXML libraries to the linker flags.

This resolves errors such as:

AutoVersioning.cpp:(.text+0x7755): undefined reference to `TiXmlNode::FirstChildElement(char const*) const'

See the included patch for additional details and comments.

Package-Manager: portage-3.0.82.2
Signed-off-by: Matthew White <mehw.is.me@proton.me>