x11-drivers/nvidia-drivers: depend on gtk+:3[X] with USE=tools
fatal error: gdk/gdkx.h: No such file or directory

nvidia-settings is already barely functional on wayland and depends
on other X libs, so users that want to skip X altogether are advised
to USE=-tools (albeit remember lose xwayland support with -X).

Skipping revbump given low-impact (even if built /then/ disable
USE=X on gtk, nvidia-settings is currently unimportant on wayland).
nvidia-drivers gets rebuild often on kernel upgrades too.

Signed-off-by: Ionen Wolkens <ionen@gentoo.org>