app-text/dictd: Update patch + fix QA warnings
Makes trivial changes to the libtool patch for correctness and silences
the follow QA warnings that were exposed with autoreconf.

 * QA Notice: Package triggers severe warnings which indicate that it
 *            may exhibit random runtime failures.
 * y.tab.c:1054:16: warning: implicit declaration of function ‘yylex’ [-Wimplicit-function-declaration]
 * y.tab.c:1240:7: warning: implicit declaration of function ‘yyerror’; did you mean ‘YYerror’? [-Wimplicit-function-declaration]
 * y.tab.c:1430:16: warning: implicit declaration of function ‘yylex’ [-Wimplicit-function-declaration]
 * y.tab.c:2212:7: warning: implicit declaration of function ‘yyerror’; did you mean ‘YYerror’? [-Wimplicit-function-declaration]

 * QA Notice: command not found:
 *
 * 	./config.status: line 784: 1.13.0=dummy.13.0: command not found

Bug: https://bugs.gentoo.org/852884
Fixes: https://github.com/gentoo/gentoo/pull/25948
Signed-off-by: orbea <orbea@riseup.net>
Closes: https://github.com/gentoo/gentoo/pull/25962
Signed-off-by: Sam James <sam@gentoo.org>