net-irc/irker: Drop python3 support as per bug #619700
irk and irkerhook.py do not support python3 yet.

  $ python3.4 ./irk
  Traceback (most recent call last):
    File "./irk", line 52, in <module>
      main()
    File "./irk", line 40, in main
      target = sys.argv[1]
  IndexError: list index out of range

  $ python3.4 ./irkerhook.py
    File "./irkerhook.py", line 459
      print message
                  ^
  SyntaxError: Missing parentheses in call to 'print'

See: https://bugs.gentoo.org/show_bug.cgi?id=619700
Package-Manager: Portage-2.3.5, Repoman-2.3.1