net-ftp/proftpd: require USE=ssl for sq modules, bug #682462
Rolf Eike Beer reports build failure on USE=-ssl setup:
    mod_sql_passwd.c:47:3: error:
       #error "OpenSSL support required (--enable-openssl)"

Reported-by: Rolf Eike Beer
Closes: https://bugs.gentoo.org/682462
Package-Manager: Portage-2.3.66, Repoman-2.3.12
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>