dev-python/numpy: Needs newer cython to build
Otherwise it fails with:
RuntimeError: Building NumPy requires Cython >= 0.29.30, found 0.29.28 at /usr/lib/python3.9/site-packages/Cython/__init__.py

Signed-off-by: Pacho Ramos <pacho@gentoo.org>