dev-db/sqlite: use correct prefixes for cross-compilation
In case `ESYSROOT` is located other than `/`, cross compilation fails
due to wrong prefixes used by configure.

For example, when the cross toolchain is under `/build/arm64-usr`,
build fails like that:

```
./configure --build=x86_64-pc-linux-gnu --host=aarch64-cros-linux-gnu
--with-sysroot=/build/arm64-usr
--with-readline-inc=-I/build/arm64-usr/usr/include/readline
--enable-tcl
./libtool --mode=compile --tag=CC aarch64-cros-linux-gnu-gcc
-O2 -pipe -mtune=generic -g -I.
-I/build/arm64-usr/var/tmp/portage/dev-db/sqlite-3.33.0/work/sqlite-src-3330000-.arm64/src
-I/usr/include -c sqlite3.c
In file included from /usr/include/features.h:489,
                 from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/stdint.h:26,
                 from sqlite3.c:13484:
/usr/include/gnu/stubs.h:7:11: fatal error: gnu/stubs-32.h: No such file
or directory
```

That happens because `CFLAGS` includes `-I/usr/include`, which is not the
correct location of cross toolchains.
The bare prefix is provided automatically by the option `--enable-tcl`.
It should be actually e.g. `-I/build/arm64-usr/usr/include`.

To make configure look up the correct path, we should specify
`--enable-tcl --with-tcl="${ESYSROOT}/usr/$(get_libdir)"`, where e.g.
`ESYSROOT` is `/build/arm64-usr`.

To avoid similar cross-toolchain issues, let's pass in
`--exec-prefix=${ESYSROOT}/usr` to the configure script.

Signed-off-by: Dongsu Park <dongsu@kinvolk.io>