net-p2p/deluge: port to EPYTEST_PLUGINS
Fixes autoload conflicts *yet again*.
```
ValueError: Plugin already registered under a different name:
twisted=<module 'pytest_twisted' from '/usr/lib/python3.13/site-packages/pytest_twisted/__init__.py'>
```

... since commit 8b9ce599af12542699d6dd47b079f9b47ff386c6 (probably) the
entrypoint exists again, and was always named something different from
the import name.

Bug: https://bugs.gentoo.org/866677
Signed-off-by: Eli Schwartz <eschwartz@gentoo.org>