dev-java/ant-ivy: Switch to httpcomponents-client, restrict to jdk:1.8
dev-java/httpcomponents-client was in
slot 4 of dev-java/commons-httpclient before.

Restrict to jdk:1.8 as it would fail with jdk-17
src/java/org/apache/ivy/util/FileUtil.java:49: error: cannot find symbol
import static java.util.jar.Pack200.newUnpacker;

Package-Manager: Portage-3.0.30, Repoman-3.0.3
Signed-off-by: Volkmar W. Pogatzki <gentoo@pogatzki.net>