sys-fs/zfs: disable systemd on musl
Needed to fix build failures on musl (where we don't
have systemd anyway):
```
zfs-mount-generator.c: In function 'line_worker':
zfs-mount-generator.c:238:24: warning: implicit declaration of function 'strndupa'; did you mean 'strndup'? [-Wimplicit-function-declaration]
  238 |                 pool = strndupa(pool, toktmp - pool);
      |                        ^~~~~~~~
      |                        strndup
zfs-mount-generator.c:238:22: warning: assignment to 'const char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  238 |                 pool = strndupa(pool, toktmp - pool);
      |                      ^
```

Reported-by: Jory A. Pratt <anarchy@gentoo.org>
Signed-off-by: Sam James <sam@gentoo.org>