media-video/obs-studio: fix dev-qt/qtbase dependency
dev-qt/qtbase with Xorg support is required to build obs-studio, else we
get build errors such as:

frontend/OBSApp.cpp:1054:60: error: no member named 'QX11Application' in
namespace 'QNativeInterface'

Closes: https://bugs.gentoo.org/960634
Closes: https://github.com/gentoo/gentoo/pull/43152
Signed-off-by: Brahmajit Das <listout@listout.xyz>
Signed-off-by: Jimi Huotari <chiitoo@gentoo.org>