gnome-base/gnome-control-center: enforce binary dependency on gtk x11 and wayland backends
Note that for >=v48.3, we currently need to hard depend on the gtk
wayland backend:
"In file included from
'../gnome-control-center-48.3/subprojects/libgxdp/src/gxdp-wayland.c:25:'
'/usr/include/gtk-4.0/gdk/wayland/gdkwayland.h:28:4: error: #error"'
```
 * QA Notice: binaries depend on Gtk's wayland-specific ABI without USE dep:
 *
 *   /usr/bin/gnome-control-center

 * QA Notice: binaries depend on Gtk's x11-specific ABI without USE dep:
 *
 *   /usr/bin/gnome-control-center
```

Closes: https://bugs.gentoo.org/960764
Signed-off-by: Lukas Schmelting <lschmelting@posteo.com>