dev-util/intel_clc: switch from --buildtype to -Dbuildtype
Followup to b95ea11330e446d0deb89ca7d78356cb2a7d0d06, which switched
meson.eclass from --buildtype to -Dbuildtype, resulting in

> ERROR: Got argument buildtype as both -Dbuildtype and --buildtype. Pick one.

Signed-off-by: Sven Wegener <swegener@gentoo.org>