sys-apps/portage: Bump to version 2.3.92
 #601252 emerge --pretend --fetchonly event loop recursion
 #709334 socks5-server.py async and await coroutine syntax
 #709746 Rename PORTAGE_LOG_FILTER_FILE_CMD from PORTAGE_LOG_FILTER_FILE
 #711322 emerge hang after src_install
 #711362 egencache AttributeError: 'NoneType' object has no attribute
         'ebuild'
 #711400 AttributeError: 'NoneType' object has no attribute 'depth'

Bug: https://bugs.gentoo.org/711148
Bug: https://bugs.gentoo.org/709334
Bug: https://bugs.gentoo.org/709746
Closes: https://bugs.gentoo.org/711322
Bug: https://bugs.gentoo.org/711362
Bug: https://bugs.gentoo.org/711400
Package-Manager: Portage-2.3.92, Repoman-2.3.20
Signed-off-by: Zac Medico <zmedico@gentoo.org>