sys-libs/ncurses: fix mingw-w64 build and runtime
*.dll.a files are required for linking on mingw-w64 targets, only delete
normal static libraries.

--enable-term-driver is required on mingw-w64, otherwise you get a host
of undefined reference to `_nc_*' errors, and possibly other windows
platforms/runtimes/toolchains.

Bug: https://bugs.gentoo.org/631468
Bug: https://bugs.gentoo.org/639670
Package-Manager: Portage-2.3.10, Repoman-2.3.3
Signed-off-by: Marty E. Plummer <hanetzer@protonmail.com>
Closes: https://github.com/gentoo/gentoo/pull/5734