media-gfx/graphviz: clarify description of gts USE flag
GTS stands for GNU Triangulated Surface Library, and is required
for sfdp to work.

Building graphiz without this flag and trying to run sfdp
leads to the following error:

    Error: remove_overlap: Graphviz not built with triangulation library

Closes: https://bugs.gentoo.org/671108