net-irc/ngircd: fix several bugs
1. USE="irc-plus" is default enabled now
2. /etc/ngircd/{,ngircd.conf} owned by root:ngircd, and update permissions
3. configure report getaddrinfo not works because of stricter compiler check:
     checking whether getaddrinfo() works... no
     configure:6303: x86_64-pc-linux-gnu-gcc -o conftest -g -O2 -pipe -W -Wall -Wpointer-arith -Wstrict-prototypes -fstack-protector -DSYSCONFDIR='"$(sysconfdir)"' -DDOCDIR='"$(docdir)"'   conftest.c  >&5
     conftest.c: In function 'main':
     conftest.c:99:9: error: implicit declaration of function 'memset' [-Wimplicit-function-declaration]

   configure.ac still use de-ANSI-fication (which is only available in
   old automake) in order to support old systems. So we can't patch
   configure.ac and run eautoreconf. see
   https://github.com/ngircd/ngircd/issues/261

   It's important to make sure ngircd-26.1-configure-getaddrinfo.patch
   works correctly for each new release.

Closes: https://bugs.gentoo.org/719256
Closes: https://bugs.gentoo.org/900082
Closes: https://bugs.gentoo.org/908349
Closes: https://bugs.gentoo.org/946998
Signed-off-by: Z. Liu <zhixu.liu@gmail.com>