app-text/xdvik: Fix compilation on GCC 14
- Casts page_info.page_labels to _Xconst char** to correct an
  incompatible pointer type
- Moves patches into an array

gui/pagesel.c: In function ‘xaw_update_list’:
gui/pagesel.c:541:41: error: passing argument 2 of ‘XawListChange’ from incompatible pointer type [-Wincompatible-pointer-types]
  541 |     XawListChange(LIST_WIDGET, page_info.page_labels, 0,
      |                                ~~~~~~~~~^~~~~~~~~~~~
      |                                         |
      |                                         char **

https://wiki.gentoo.org/wiki/Modern_C_porting

Unfortunately upstream rejected the PR due to backwards compatability
issues

Upstream PR: https://github.com/TeX-Live/texlive-source/pull/64
Mailing List: https://tug.org/pipermail/tex-k/2024-February/004008.html
Closes: https://bugs.gentoo.org/919069
Signed-off-by: Christopher Fore <csfore@posteo.net>
Closes: https://github.com/gentoo/gentoo/pull/35546
Signed-off-by: Florian Schmaus <flow@gentoo.org>