net-firewall/nftables: Depend on >=net-libs/libnftnl-1.1.5
Although upstreams reports that nftables 0.9.3 depends on
libnftnl 1.1.4 or higher. Using said version results on the
following errors:
netlink.c: In function ‘netlink_delinearize_chain’:
netlink.c:423:38: error: ‘NFTNL_CHAIN_DEVICES’ undeclared
(first use in this function); did you mean ‘NFTNL_CHAIN_DEV’?
   } else if (nftnl_chain_is_set(nlc, NFTNL_CHAIN_DEVICES)) {
                                      ^~~~~~~~~~~~~~~~~~~
                                      NFTNL_CHAIN_DEV
netlink.c:423:38: note: each undeclared identifier is reported
only once for each function it appears in
netlink.c: In function ‘netlink_delinearize_obj’:
netlink.c:1049:27: error: ‘NFTNL_OBJ_SYNPROXY_MSS’ undeclared
(first use in this function); did you mean ‘NFTNL_EXPR_SYNPROXY_MSS’?
    nftnl_obj_get_u16(nlo, NFTNL_OBJ_SYNPROXY_MSS);
                           ^~~~~~~~~~~~~~~~~~~~~~
                           NFTNL_EXPR_SYNPROXY_MSS
netlink.c:1051:26: error: ‘NFTNL_OBJ_SYNPROXY_WSCALE’ undeclared
(first use in this function); did you mean ‘NFTNL_EXPR_SYNPROXY_WSCALE’?
    nftnl_obj_get_u8(nlo, NFTNL_OBJ_SYNPROXY_WSCALE);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~
                          NFTNL_EXPR_SYNPROXY_WSCALE
netlink.c:1053:27: error: ‘NFTNL_OBJ_SYNPROXY_FLAGS’ undeclared (first
use in this function); did you mean ‘NFTNL_EXPR_SYNPROXY_FLAGS’?
    nftnl_obj_get_u32(nlo, NFTNL_OBJ_SYNPROXY_FLAGS);
                           ^~~~~~~~~~~~~~~~~~~~~~~~
                           NFTNL_EXPR_SYNPROXY_FLAGS
netlink.c: In function ‘netlink_delinearize_flowtable’:
netlink.c:1137:3: warning: implicit declaration of function
‘nftnl_flowtable_get_u64’; did you mean ‘nftnl_flowtable_get_u32’?
[-Wimplicit-function-declaration]
   nftnl_flowtable_get_u64(nlo, NFTNL_FLOWTABLE_HANDLE);
   ^~~~~~~~~~~~~~~~~~~~~~~
   nftnl_flowtable_get_u32
netlink.c:1137:32: error: ‘NFTNL_FLOWTABLE_HANDLE’ undeclared (first
use in this function); did you mean ‘NFTA_FLOWTABLE_HANDLE’?
   nftnl_flowtable_get_u64(nlo, NFTNL_FLOWTABLE_HANDLE);
                                ^~~~~~~~~~~~~~~~~~~~~~
                                NFTA_FLOWTABLE_HANDLE

Depend instead on version 1.1.5 or higher with which the
compilation suceeds.

Closes: https://bugs.gentoo.org/701976
Signed-off-by: Francisco Blas Izquierdo Riera (klondike) <klondike@gentoo.org>
Package-Manager: Portage-2.3.76, Repoman-2.3.11
Signed-off-by: Matthew Thode <prometheanfire@gentoo.org>