profiles: mask dev-lang/ruby[jit] in base, unmask on amd64/arm64
Reported by gyakovlev on presumably ppc64 (which is a Rust arch, but Rust
is necessary-but-not-sufficient for YJIT):
```
In file included from yjit.c:24:
yjit.h:24:3: error: #error YJIT unsupported platform
24 | # error YJIT unsupported platform
|   ^~~~~
```

Signed-off-by: Sam James <sam@gentoo.org>