app-emulation/protontricks: bump to 1.4.1
protontricks now have a setup-time dependency on
dev-python/setuptools_scm, which means we have to use use release
tarballs from PyPI rather than from GitHub - the latter cause builds to
fail with

LookupError: setuptools-scm was unable to detect version for '/.../app-emulation/protontricks-1.4.1/work/protontricks-1.4.1'.
Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

The upshot of the above is that we can no longer run tests because
the necessary files are not included in PyPI tarballs.

Signed-off-by: Marek Szuba <marecki@gentoo.org>