net-p2p/syncthing-1.3.1: temporarily restrict tests if USE=tools is set
For some reason the switch to go-module.eclass has resulted in the
following test failure appearing repeatedly when USE=tools is set:

--- FAIL: TestAPIServiceRequests (5.45s)
    api_test.go:394: Testing /rest/db/completion?device=<snip>
    api_test.go:394: Testing /rest/db/file?folder=default&file=something ...
    api_test.go:394: Testing /rest/db/ignores?folder=default ...
    api_test.go:394: Testing /rest/db/need?folder=default ...
    api_test.go:394: Testing /rest/db/status?folder=default ...
    api_test.go:394: Testing /rest/db/browse?folder=default ...
    api_test.go:394: Testing /rest/stats/device ...
    api_test.go:394: Testing /rest/stats/folder ...
    api_test.go:394: Testing /rest/svc/deviceid?id=<snip>
    api_test.go:394: Testing /rest/svc/lang ...
    api_test.go:394: Testing /rest/svc/report ...
    api_test.go:419: Unexpected error requesting /rest/svc/report: Get
http://127.0.0.1:36607/rest/svc/report: net/http: request canceled
(Client.Timeout exceeded while awaiting headers)
    api_test.go:394: Testing /rest/system/browse?current=~ ...
    api_test.go:394: Testing /rest/system/config ...
    api_test.go:394: Testing /rest/system/config/insync ...
    api_test.go:394: Testing /rest/system/connections ...
    api_test.go:394: Testing /rest/system/discovery ...
    api_test.go:394: Testing /rest/system/error?since=0 ...
    api_test.go:394: Testing /rest/system/ping ...
    api_test.go:394: Testing /rest/system/status ...
    api_test.go:394: Testing /rest/system/version ...
    api_test.go:394: Testing /rest/system/debug ...
    api_test.go:394: Testing /rest/system/log?since=0 ...
    api_test.go:394: Testing /rest/system/log.txt?since=0 ...
FAIL
FAIL    github.com/syncthing/syncthing/lib/api  66.295s

This may or may not be a consequence of the fact Syncthing upstream
doesn't fully support go-1.13 yet, as shown by the fact their CI
configuration uses the very-much-not-recommended workaround of deleting
go.sum. Anyway, since the tests pass with USE=-tools and there have been
requests for Syncthing ebuilds with go-1.13 support, disable testing
when USE=tools is set until the problem has been resolved.

Package-Manager: Portage-2.3.76, Repoman-2.3.16
Signed-off-by: Marek Szuba <marecki@gentoo.org>