dev-ada/e3-core: add missing ptyprocess test dep
FAILED tests/tests_e3/os/process/main_test.py::test_rlimit_ctrl_c - ImportError: ptyprocess is needed to run this tests
FAILED tests/tests_e3/os/process/main_test.py::test_rlimit_foreground_option - ImportError: ptyprocess is needed to run this tests
= 2 failed, 431 passed, 18 skipped, 1 deselected, 1 xfailed, 4 xpassed, 28 warnings in 47.69s =
<sys>:0: ResourceWarning: unclosed file <_io.BufferedReader name=19>
<sys>:0: ResourceWarning: unclosed file <_io.BufferedReader name=18>
<sys>:0: ResourceWarning: unclosed file <_io.BufferedReader name=17>
 * ERROR: dev-ada/e3-core-22.6.0-r4::gentoo failed (test phase):
 *   pytest failed with python3.13

Bug: https://bugs.gentoo.org/966463
Signed-off-by: Sam James <sam@gentoo.org>