dev-util/include-what-you-use: worjaround <stddef.h> lookup failure, bug #625972
libclangDriver treats path to include files as stable relative
to clang binary: when we run /usr/lib64/llvm/4/bin/clang it resolves
<stddef.h> the following way:
    "/usr/lib64/llvm/4/bin/" + "../../../../lib/clang/4.0.1/include/stddef.h"

Unfortunately when someone reuses clang driver to build a new tool
heared lookup breaks if final tool resides in "/usr/bin":
    "/usr/bin/" + "../../../../lib/clang/4.0.1/include/stddef.h"
causing file open failures in case of include-what-you-use:
    /usr/include/wchar.h:39:11: fatal error: 'stdarg.h' file not found
    # include <stdarg.h>
              ^~~~~~~~~~

The workaround is to install executable to the same directory as clang itself.

Reported-by: Michał Bartoszkiewicz
Bug: https://bugs.gentoo.org/625972
Package-Manager: Portage-2.3.6, Repoman-2.3.3