dev-python/flake8: Fix incorrect mccage dep in DEPEND
This is causing a conflict with itself with FEATURES=test enabled.
I discovered this conflict attempting to bump dev-python/treq.
Also, with this correction, there is one test failure:

>       assert parsed_config['ignore'] == ['E123', 'W234', 'E111']
E       assert ['# Disable E...e E111\nE111'] == ['E123', 'W234', 'E111']
E         At index 0 diff: '# Disable E123\nE123' != 'E123'
E         Use -v to get the full diff

tests/unit/test_merged_config_parser.py:201: AssertionError

Package-Manager: portage-2.3.1_p4