media-video/ffmpeg: depend on >=amf-headers-1.5.0 in live
Upcoming ffmpeg-8.1 started to use the DisplayCapture.h header which
causes a build failure with <1.5.0. If really needed we could backport
the fix to 1.4.x but I do not see much of a reason to right now.

DisplayCapture.h:43:8: error: expected identifier or '(' [...]

Signed-off-by: Ionen Wolkens <ionen@gentoo.org>