dev-libs/mpc: remove 'mpfr_add_one_ulp' use, mpfr-4.0.0 fix part 2
It's a backport of https://scm.gforge.inria.fr/anonscm/gitweb?p=mpc/mpc.git;a=commitdiff;h=5eaa17651b759c7856a118835802fecbebcf46ad
("replace obsolete mpfr_add_one_ulp/mpfr_sub_one_ulp functions")

mpfr-4.0.0 does not provide those functions anymore.
Unfortunately 'mpc' does not fail to build against such
mpfr but links broken library. One of the hints is usage
of undeclared function:
    mpc-1.0.3/src/mpc-impl.h:63:29: warning: implicit declaration of function
    ‘mpfr_add_one_ulp’ [-Wimplicit-function-declaration]

Package-Manager: Portage-2.3.19, Repoman-2.3.6