net-libs/serf: fix dev-vcs/subversion build fail
With the previous backported LibreSSL patch the build in
dev-vcs/subversion fails with an undefined reference to
CRYPTO_malloc_init() which should be used with LibreSSL
and not OpenSSL. To avoid this unintended issue the patch
is changed to check only for LIBRESSL_VERSION_NUMBER.

When the next serf release happens this patch can be removed
and the new upstream cmake build system may be preferable.

Closes: https://bugs.gentoo.org/906123
Signed-off-by: orbea <orbea@riseup.net>