dev-java/ant-core: raise minimum Java version to 9
While Ant runs on Java 8, it is hit by API changes of ByteBuffer.flip():
The flip() method returns Buffer in Java 8 and ByteBuffer in Java 9. If
Ant is now emerged and build using Java 8, and then run with Java 9 (or
higher), a NoSuchMethodError is potentially thrown invoking ant:

BUILD FAILED
/var/tmp/portage/net-vpn/i2p-1.6.1/work/i2p-1.6.1/build.xml:1634: java.lang.NoSuchMethodError: java.nio.CharBuffer.flip()Ljava/nio/CharBuffer;
	at org.apache.tools.ant.util.ReaderInputStream.<init>(ReaderInputStream.java:81)
	at org.apache.tools.ant.util.ReaderInputStream.<init>(ReaderInputStream.java:66)
	at org.apache.tools.ant.util.ReaderInputStream.<init>(ReaderInputStream.java:118)
	at org.apache.tools.ant.util.ReaderInputStream.<init>(ReaderInputStream.java:93)
	at org.apache.tools.ant.taskdefs.Concat$ConcatResource.getInputStream(Concat.java:421)
	at org.apache.tools.ant.util.ResourceUtils.copyUsingStreams(ResourceUtils.java:766)
	at org.apache.tools.ant.util.ResourceUtils.copyResource(ResourceUtils.java:437)
	at org.apache.tools.ant.taskdefs.Concat.execute(Concat.java:802)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
	at org.apache.tools.ant.Main.runBuild(Main.java:827)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)

Raising the minimum required Java version to 9 fixes this.

Closes: https://bugs.gentoo.org/839093
Signed-off-by: Florian Schmaus <flow@gentoo.org>