dev-python/nbconvert: depend on newer traitlets (fixes test failure)
Fix various failures in tests ending with:
```
E             File "/usr/lib/python3.9/site-packages/traitlets/config/loader.py", line 931, in __call__
E               namespace._flags.append(self.flag)
E           AttributeError: 'Namespace' object has no attribute '_flags'

cmd        = ['/usr/bin/python3.9',
```

Signed-off-by: Sam James <sam@gentoo.org>