sci-libs/scalapack: -fallow-argument-mismatch for gcc v10
Make new error introduced in gcc v10 nonfatal:

	Error: Rank mismatch between actual argument at (1) and actual argument
	at (2) (scalar and rank-1)

More info: https://gcc.gnu.org/gcc-10/porting_to.html

Closes: https://bugs.gentoo.org/727340

Signed-off-by: Alexei Colin <acolin@isi.edu>