app-text/poppler: fix pkg-config
if cairo and introspection are enabled, giscanner is called and
PKG_CONFIG must be defined to avoid 'pkg-config' by default.
> ERROR: pkg-config: error executing command ['pkg-config', '--cflags',
> 'gobject-2.0', 'glib-2.0', 'cairo-gobject', 'gio-2.0', 'gmodule-2.0',
> 'gio-unix-2.0']: [Errno 2] No such file or directory: 'pkg-config'

Signed-off-by: Nicolas PARLANT <nicolas.parlant@parhuet.fr>
Part-of: https://github.com/gentoo/gentoo/pull/45612
Closes: https://github.com/gentoo/gentoo/pull/45612
Signed-off-by: Sam James <sam@gentoo.org>