app-emulation/qemu: bdepend on dev-util/gdbus-codegen
`dbus_display` is automagic. Given it only seems at a glance to need
gdbus-codegen, just BDEPEND on it unconditionally. Patches welcome
to make it conditional w/ rationale, but leaving it automagic is obviously
worse, so fix that:

> FAILED: ui/dbus-display1.h ui/dbus-display1.c
> /usr/bin/gdbus-codegen ui/dbus-display1.xml --glib-min-required 2.64 --output-directory /var/tmp/portage/app-emulation/qemu-10.0.5/work/qemu-10.0.5/softmmu-build/ui --interface-prefix org.qemu. --c-namespace QemuDBus --generate-c-code dbus-display1
> Traceback (most recent call last):
>   File "/usr/bin/gdbus-codegen", line 25, in <module>
>    from gdbus_codegen import codegen_main
>   File "/usr/lib/python3.12/site-packages/gdbus_codegen/codegen_main.py", line 30, in <module>
>     from . import dbustypes
>   File "/usr/lib/python3.12/site-packages/gdbus_codegen/dbustypes.py", line 22, in <module>
>     from . import utils
>   File "/usr/lib/python3.12/site-packages/gdbus_codegen/utils.py", line 22, in <module>
>     import packaging.version
> ModuleNotFoundError: No module named 'packaging'

Minimum version is because of 9e8d0acdcb56d57dfdfef79eb7297591701f582a.

Signed-off-by: Sam James <sam@gentoo.org>