media-libs/zimg: tweak for gcc-10, bug #721676
The build fails as:

```
src/zimg/colorspace/matrix3.cpp:20:7:
  error: 'size_t' was not declared in this scope; did you mean 'std::size_t'?
   20 |  for (size_t i = 0; i < 3; ++i) {
      |       ^~~~~~
      |       std::size_t
```

Direct backport of upstream 9ae36d7d5f74 ("Update matrix3.cpp")
which adds missing <cstddef> include needed for 'size_t'.

Reported-by: Patrick McLean
Closes: https://bugs.gentoo.org/721676
Package-Manager: Portage-2.3.99, Repoman-2.3.22
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>