net-misc/dahdi: Fix build with clang-16 and migrate to linux-mod-r1 eclass
Ran into -Werror issues (silly stuff like implicit fallthrough), but
-Werror is no longer passed with linux-mod-r1. Not that this stops
ones like the -Werror=incompatible-pointer-types wrt bug #906179, so
that issue still applies when using kernel 6.3(?). Was fine with
a stable 6.1.28 gcc-13 kernel, albeit ftr it still failed with a
clang-16 one giving:

dahdi-linux-3.2.0/drivers/dahdi/wctc4xxp/base.c:646:9: error:
passing 'const unsigned char *' to parameter of type 'void *'
discards qualifiers
[-Werror,-Wincompatible-pointer-types-discards-qualifiers]
memcpy(netdev->dev_addr, our_mac, sizeof(our_mac));

fwiw MODULES_ARGS+=( KCFLAGS=-Wno-error=incompatible-pointer-types )
lets it build with both 6.3.4 kernel-bin (gcc) and 6.1.28 (clang+lto),
not that this is a great fix and may hide more notable issues (may be
better than being semi-unbuildable for now though)

wrt old depmod find, should not be necessary given eclass adds DEPMOD=:

The patch fixes some -Wincompatible-pointer-types-discards-qualifiers,
that are comming from upstream commit
https://github.com/torvalds/linux/commit/2a81ada32f0e584fc0c943e0d3a8c9f4fae411d6
that changes the struct bus_type.uevent() take a const *, thus
making it possible to built with clang-16.

Closes: https://bugs.gentoo.org/906179
Co-authored-by: Ionen Wolkens <ionen@gentoo.org>
Signed-off-by: Brahmajit Das <brahmajit.xyz@gmail.com>