dev-db/redis: fix build w/ clang
When using "-std=c99" while compiling C++, g++ only issues a warning:

> cc1plus: warning: command-line option '-std=c99' is valid for C/ObjC but not for C++

However, clang++ reports an error:

> error: invalid argument '-std=c99' not allowed with 'C++

Therefore, remove "-std=c99" for deps/fast_float/Makefile as well, otherwise the build fails with:

> clang: error: no such file or directory: '../deps/fast_float/libfast_float.a

Signed-off-by: Z. Liu <zhixu.liu@gmail.com>
Part-of: https://github.com/gentoo/gentoo/pull/43934
Closes: https://github.com/gentoo/gentoo/pull/43934
Signed-off-by: Petr Vaněk <arkamar@gentoo.org>