app-admin/syslog-ng: add 4.10.2
There's a bunch of refactoring in the build system but I don't think we
needed any changes in the end.

No LTO because:
```
modules/add-contextual-data/tests/.libs/test_context_info_dbS.c:54:12: error: type of 'context_info_db_insert' does not match original declaration [-Werror=lto-type-mismatch]
   44 | void context_info_db_insert(ContextInfoDB *self,
      |      ^
./modules/add-contextual-data/context-info-db.h:44:6: note: type 'void' should match type 'int'
./modules/add-contextual-data/context-info-db.h:44:6: note: 'context_info_db_insert' was previously declared here
modules/add-contextual-data/tests/.libs/test_context_info_dbS.c:48:12: error: type of 'context_info_db_contains' does not match original declaration [-Werror=lto-type-mismatch]
./modules/add-contextual-data/context-info-db.h:47:10: note: type mismatch in parameter 1
   47 | gboolean context_info_db_contains(ContextInfoDB *self,
      |          ^
```

Bug: https://bugs.gentoo.org/964557
Signed-off-by: Sam James <sam@gentoo.org>