llvm-runtimes/compiler-rt-sanitizers: prevent -fstack-protector in *FLAGS
It causes the build to error since e.g. Sanitizer-x86_64-Test-Nolibc
builds with, unsurprisingly, `-static -nostdlib` resulting in

```
/usr/bin/x86_64-pc-linux-gnu-ld.bfd: sanitizer_nolibc_test_main.x86_64.o: in function `_start':
..../sanitizer_nolibc_test_main.cpp:(.text+0x29): undefined reference to `__stack_chk_fail'
```

The cmake files check for -fno-stack-protector support already, and pass
it to various parts if possible. But apparently not this. :P

Acked-by: Sam James <sam@gentoo.org>
Signed-off-by: Eli Schwartz <eschwartz@gentoo.org>